### ISSUE TITLE
Keyboard Wizard affecting Controls GUI

### ISSUE THREAD

**Issue by ariosos** [MrNerdy42/Keyboard-Wizard#23] opened 2019-10-14 04:14 UTC
When trying to bind a control to CTRL, SHIFT or ALT using the Controls GUI, the selection will remain on the button and take any other key that gets entered. I only have Keyboard Wizard added.

Steps to Reproduce:
1 - Create a new forge instance and only install Keyboard Wizard (v1.7.1)
2 - Go to Options->Controls.
3 - Select any keybinding and press CTRL, SHIFT, or ALT.

Result: The selection will remain until another key or mouse button is pressed.

![image](https://user-images.githubusercontent.com/7917753/66729095-21c92680-ee17-11e9-9225-8361fc417178.png)
![image](https://user-images.githubusercontent.com/7917753/66729101-2b528e80-ee17-11e9-8bb7-10b91a377a29.png)

I know there is a work-around to set openFromControlsGui to False, but this happens when it's the only mod being used. (Unless Forge is overriding the controls GUI?)

**Comment by fuzzyweapon** [comment] 2019-11-17 19:20
This is a minecraft bug.

**Comment by MrNerdy42** [comment] 2019-12-11 03:23
As much as I'd like to believe that, this is my mod's fault. I'll have to look into why in the world it's happening. 

The way I override the controls gui is pretty janky, I basically copied the controls gui code line for line and added a button. It makes me cringe just typing it. I probably screwed something up in my duplicate of the controls gui.

**Comment by MrNerdy42** [comment] 2019-12-11 22:18
I should be using reflection to do this, duh. I really shouldn't slap things together on 3 hours of sleep and 8 cups of coffee. This will be fixed ASAP

**Comment by MrNerdy42** [comment] 2019-12-13 01:04
Done

**Closed as completed by MrNerdy42** 2019-12-13 01:04 UTC
Labels: bug
